
name: multiple antifacts

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi > world.txt
      - uses: actions/upload-artifact@v2
        with:
        path: world.txt

      - run: echo howdy > ext ra-file.txt
      - uses: actions/upload-artifact@v2
        with:
        path: extra-file.txt

      - run: echo hello > world.txt
      - uses: actions/upload-artifact@v2
         with:
         path: world.txt
